### ISSUE TITLE
Sampling error in NRT 

### ISSUE THREAD

**Issue by payalchandak** [mmcdermott/nested_ragged_tensors#38]
```
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nested_ragged_tensors.ragged_numpy import *
>>> import nested_ragged_tensors
>>> nested_ragged_tensors.__version__
'0.0.7'
>>> J = JointNestedRaggedTensorDict({
... "dim0/time_delta_days": [0.00972222, 0.03333334],
... "dim1/lengths": [2, 1],
... "dim1/code": [[14, 15], [7]],
... "dim1/numeric_value": [[-0.0539279, 1.1927332], [float('nan')]],
... "dim1/bounds": [2, 3],
... }, schema={
... "dim1/time_delta_days": "float32",
... "dim2/code": "uint8",
... "dim2/numeric_value": "float32"
... })
>>> len(J)
2
>>> J[1:1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 613, in __getitem__
    return self._slice(self._get_slice_indices(idx))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 1321, in _get_slice_indices
    return self._get_slice_indices_internal(S, 0, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 1339, in _get_slice_indices_internal
    for key in self.keys_at_dim(starting_dim):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 498, in keys_at_dim
    return {k for k in self.keys() if self._get_dim(k) == dim}
                                      ^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 482, in _get_dim
    raise KeyError(f"Key {key} not found in {', '.join(self.tensors.keys())}")
KeyError: 'Key dim0 not found in dim0/dim0/time_delta_days, dim0/dim1/lengths, dim1/bounds, dim1/dim1/code, dim1/dim1/numeric_value, dim0/dim1/bounds'
>>> J[1:2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 613, in __getitem__
    return self._slice(self._get_slice_indices(idx))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 1321, in _get_slice_indices
    return self._get_slice_indices_internal(S, 0, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 1339, in _get_slice_indices_internal
    for key in self.keys_at_dim(starting_dim):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 498, in keys_at_dim
    return {k for k in self.keys() if self._get_dim(k) == dim}
                                      ^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/nested_ragged_tensors/ragged_numpy.py", line 482, in _get_dim
    raise KeyError(f"Key {key} not found in {', '.join(self.tensors.keys())}")
KeyError: 'Key dim0 not found in dim0/dim0/time_delta_days, dim0/dim1/lengths, dim1/bounds, dim1/dim1/code, dim1/dim1/numeric_value, dim0/dim1/bounds'
```

**Comment by mmcdermott** [comment]
So I think this is largely a consequence of using processed names as inputs when you should use raw names. E.g., if you try just using `time_delta_days`, `code`, and `numeric_value`, I think you'll find that things work as expected? Or does that still error for you?

**Comment by mmcdermott** [comment]
Closing as I think this is covered by #42.
